export default {
  HeroIcons: {
    link: "https://icon-sets.iconify.design/heroicons/",
    missing: ["cropper", "sort"],
    icons: {
      "arrow-left": "heroicons:chevron-left-solid",
      "arrow-right": "heroicons:chevron-right-solid",
      "arrow-up": "heroicons:chevron-up-solid",
      "arrow-down": "heroicons:chevron-down-solid",
      plus: "heroicons:plus",
      minus: "heroicons:minus",
      close: "heroicons:x-mark",
      check: "heroicons:check-16-solid",
      error: "heroicons:exclamation-circle",
      warning: "heroicons:exclamation-triangle",
      info: "heroicons:information-circle",
      logout: "heroicons:arrow-right-end-on-rectangle-20-solid",
      calendar: "heroicons:calendar-days-16-solid",
      camera: "heroicons:camera",
      heart: "heroicons:heart",
      home: "heroicons:home",
      search: "heroicons:magnifying-glass",
      marker: "heroicons:map-pin",
      map: "heroicons:map",
      "edit-pencil": "heroicons:pencil-square",
      pencil: "heroicons:pencil",
      photo: "heroicons:photo",
      trash: "heroicons:trash",
      "filled-error": "heroicons:exclamation-circle-solid",
      "filled-info": "heroicons:information-circle-16-solid",
      "filled-warning": "heroicons:exclamation-triangle-solid",
      "filled-camera": "heroicons:camera-solid",
      "filled-heart": "heroicons:heart-solid",
      "filled-home": "heroicons:home-20-solid",
      "filled-marker": "heroicons:map-pin-solid",
      "filled-map": "heroicons:map-20-solid",
      "filled-pencil": "heroicons:pencil-solid",
      "filled-edit-pencil": "heroicons:pencil-square-solid",
      "filled-photo": "heroicons:photo-solid",
      "filled-trash": "heroicons:trash-20-solid",
    },
  },
  Unicons: {
    link: "https://icon-sets.iconify.design/uil/",
    missing: [],
    icons: {
      "arrow-left": "uil:angle-left-b",
      "arrow-right": "uil:angle-right-b",
      "arrow-up": "uil:angle-up",
      "arrow-down": "uil:angle-down",
      sort: "uil:direction",
      sort1: "uil:sort",
      check: "uil:check",
      "circle-check": "uil:check-circle",
      close: "uil:multiply",
      plus: "uil:plus",
      calendar: "uil:calendar-alt",
      camera: "uil:camera",
      compass: "uil:compass",
      "edit-pencil": "uil:edit",
      "edit-pencil-1": "uil:edit-alt",
      pencil: "uil:pen",
      error: "uil:exclamation-circle",
      warning: "uil:exclamation-circle",
      info: "uil:info-circle",
      home: "uil:estate",
      logout: "uil:exit",
      heart: "uil:heart-alt",
      photo: "uil:image",
      photo1: "uil:scenery",
      map: "uil:map",
      marker: "uil:map-marker",
      sign: "uil:sign-left",
      search: "uil:search",
      trash: "uil:trash-alt",
      crop: "uil:crop-alt",
    },
  },
  Iconoir: {
    link: "https://icon-sets.iconify.design/iconoir/",
    missing: ["close", "search"],
    icons: {
      "arrow-left": "iconoir:nav-arrow-left",
      "arrow-right": "iconoir:nav-arrow-right",
      "arrow-up": "iconoir:nav-arrow-up",
      "arrow-down": "iconoir:nav-arrow-down",
      check: "iconoir:check",
      "circle-check": "iconoir:check-circle",
      minus: "iconoir:minus",
      plus: "iconoir:plus",
      sort: "iconoir:arrow-separate-vertical",
      calendar: "iconoir:calendar",
      camera: "iconoir:camera",
      compass: "iconoir:compass",
      crop: "iconoir:crop",
      "edit-pencil": "iconoir:edit",
      pencil: "iconoir:edit-pencil",
      heart: "iconoir:heart",
      home: "iconoir:home-simple",
      logout: "iconoir:log-out",
      maker: "iconoir:map-pin",
      map: "iconoir:map",
      photo: "iconoir:media-image",
      photos: "iconoir:media-image-list",
      trash: "iconoir:trash",
      error: "iconoir:warning-circle",
      info: "iconoir:info-circle",
      "filled-info": "iconoir:info-circle-solid",
      "filled-error": "iconoir:warning-circle-solid",
    },
  },
  "Material Line Icons": {
    link: "https://icon-sets.iconify.design/line-md/",
    missing: ["camera", "cropper"],
    icons: {
      "arrow-left": "line-md:chevron-left",
      "arrow-right": "line-md:chevron-right",
      "arrow-down": "line-md:chevron-down",
      "arrow-up": "line-md:chevron-up",
      error: "line-md:alert-circle",
      close: "line-md:close",
      close1: "line-md:remove",
      check: "line-md:confirm",
      "circle-check": "line-md:circle-to-confirm-circle-transition",
      minus: "line-md:minus",
      plus: "line-md:plus",
      search: "line-md:search",
      calendar: "line-md:calendar",
      compass: "line-md:compass",
      "edit-pencil": "line-md:edit",
      home: "line-md:home-simple",
      heart: "line-md:heart",
      photo: "line-md:image",
      logout: "line-md:login",
      marker: "line-md:map-marker",
      "marker-filled": "line-md:map-marker-alt-filled",
      pencil: "line-md:pencil",
    },
  },
  "Material Symbols": {
    link: "https://icon-sets.iconify.design/material-symbols/",
    missing: ["sort"],
    icons: {
      "arrow-left": "material-symbols:chevron-left-rounded",
      "arrow-right": "material-symbols:chevron-right-rounded",
      "arrow-up": "material-symbols:keyboard-arrow-up-rounded",
      "arrow-down": "material-symbols:keyboard-arrow-down-rounded",
      plus: "material-symbols:add-2-rounded",
      minus: "material-symbols:remove-rounded",
      close: "material-symbols:close-rounded",
      "filled-warning": "material-symbols:warning-rounded",
      warning: "material-symbols:warning-outline-rounded",
      info: "material-symbols:info-outline",
      check: "material-symbols:check-rounded",
      "circle-check": "material-symbols:check-circle-outline-rounded",
      camera: "material-symbols:photo-camera-outline",
      "filled-camera": "material-symbols:photo-camera-rounded",
      crop: "material-symbols:crop",
      delete: "material-symbols:delete-outline-rounded",
      "filled-delete": "material-symbols:delete-rounded",
      "filled-home": "material-symbols:home-rounded",
      home: "material-symbols:home-outline-rounded",
      photos: "material-symbols:imagesmode-outline",
      photo: "material-symbols:imagesmode",
      logout: "material-symbols:login-rounded",
      search: "material-symbols:search-rounded",
      map: "material-symbols:map-outline",
      "edit-pencil": "material-symbols:edit-square-outline-rounded",
      pencil: "material-symbols:edit-outline-rounded",
      marker: "material-symbols:location-on-outline",
      "filled-marker": "material-symbols:location-on-rounded",
      calender: "material-symbols:calendar-month-outline-rounded",
      "filled-calendar": "material-symbols:calendar-month-rounded",
    },
  },
  "Mono Icons": {
    link: "https://icon-sets.iconify.design/mi/",
    icons: {
      "arrow-left": "mi:chevron-left",
      "arrow-right": "mi:chevron-right",
      "arrow-down": "mi:chevron-down",
      "arrow-up": "mi:chevron-up",
      plus: "mi:add",
      minus: "mi:remove",
      check: "mi:check",
      "circle-check": "mi:circle-check",
      info: "mi:circle-information",
      error: "mi:circle-warning",
      compass: "mi:compass",
      map: "mi:map",
      close: "mi:close",
      home: "mi:home",
      heart: "mi:heart",
      camera: "mi:camera",
      calendar: "mi:calendar",
      pencil: "mi:edit",
      "edit-pencil": "mi:edit-alt",
      trash: "mi:delete",
      logout: "mi:log-in",
      sort: "mi:select",
      marker: "mi:location",
      search: "mi:search",
      photo: "mi:image",
    },
  },
  "Gravity UI Icons": {
    link: "https://icon-sets.iconify.design/gravity-ui/",
    missing: ["close"],
    icons: {
      logout: "gravity-ui:arrow-right-to-square",
      "arrow-down": "gravity-ui:chevron-down",
      "arrow-left": "gravity-ui:chevron-left",
      "arrow-right": "gravity-ui:chevron-right",
      "arrow-up": "gravity-ui:chevron-up",
      sort: "gravity-ui:chevrons-expand-vertical",
      check: "gravity-ui:check",
      "circle-check": "gravity-ui:circle-check",
      calendar: "gravity-ui:calendar",
      camera: "gravity-ui:camera",
      error: "gravity-ui:circle-exclamation",
      "filled-error": "gravity-ui:circle-exclamation-fill",
      warning: "gravity-ui:triangle-exclamation",
      "filled-warning": "gravity-ui:triangle-exclamation-fill",
      info: "gravity-ui:circle-info",
      "filled-info": "gravity-ui:circle-info-fill",
      compass: "gravity-ui:compass",
      crop: "gravity-ui:crop",
      home: "gravity-ui:house",
      marker: "gravity-ui:map-pin",
      minus: "gravity-ui:minus",
      search: "gravity-ui:magnifier",
      "edit-pencil-1": "gravity-ui:pencil-to-line",
      pencil: "gravity-ui:pencil",
      "edit-pencil": "gravity-ui:pencil-to-square",
      photo: "gravity-ui:picture",
      photos: "gravity-ui:copy-picture",
      trash: "gravity-ui:trash-bin",
      heart: "gravity-ui:heart",
      "filled-heart": "gravity-ui:heart-fill",
    },
  },
  "System UIcons": {
    link: "https://icon-sets.iconify.design/system-uicons/",
    missing: ["check circle"],
    icons: {
      "arrow-right": "system-uicons:chevron-right",
      "arrow-left": "system-uicons:chevron-left",
      "arrow-down": "system-uicons:chevron-down",
      "arrow-up": "system-uicons:chevron-up",
      plus: "system-uicons:plus",
      minus: "system-uicons:minus",
      close: "system-uicons:close",
      logout: "system-uicons:enter",
      calendar: "system-uicons:calendar-month",
      pencil: "system-uicons:pen",
      "edit-pencil": "system-uicons:create",
      compass: "system-uicons:compass",
      "home-1": "system-uicons:home",
      home: "system-uicons:home-door",
      marker: "system-uicons:location",
      heart: "system-uicons:heart",
      check: "system-uicons:check",
      sort: "system-uicons:chevron-open",
      "camera-1": "system-uicons:camera",
      camera: "system-uicons:camera-alt",
      photo: "system-uicons:picture",
      trash: "system-uicons:trash",
      crop: "system-uicons:crop",
      error: "system-uicons:warning-circle",
      info: "system-uicons:info-circle",
      search: "system-uicons:search",
    },
  },
  "Pepicons Print": {
    link: "https://icon-sets.iconify.design/pepicons-print/",
    missing: ["search", "cropper"],
    icons: {
      "arrow-left": "pepicons-print:angle-left",
      "arrow-right": "pepicons-print:angle-right",
      "arrow-up": "pepicons-print:angle-up",
      "arrow-down": "pepicons-print:angle-down",
      calendar: "pepicons-print:calendar",
      logout: "pepicons-print:enter",
      heart: "pepicons-print:heart",
      "filled-heart": "pepicons-print:heart-filled",
      home: "pepicons-print:house",
      info: "pepicons-print:info-circle",
      "filled-info": "pepicons-print:info-circle-filled",
      error: "pepicons-print:exclamation-circle",
      "filled-error": "pepicons-print:exclamation-circle-filled",
      close: "pepicons-print:line-slant-up-off",
      minus: "pepicons-print:line-x",
      pencil: "pepicons-print:pen",
      camera: "pepicons-print:photo-camera",
      photo: "pepicons-print:photo",
      marker: "pepicons-print:pinpoint",
      "marker-1": "pepicons-print:map",
      plus: "pepicons-print:plus",
      trash: "pepicons-print:trash",
    },
  },
  Marketeq: {
    link: "https://icon-sets.iconify.design/marketeq/",
    missing: ["chevrons(left, right, up, down)", "crop", "close"],
    icons: {
      plus: "marketeq:plus",
      "check-box": "marketeq:check-mark-square-2",
      "circle-check": "marketeq:check-circle",
      error: "marketeq:caution-sign-circle",
      calendar: "marketeq:date",
      "edit-pencil": "marketeq:create-note",
      trash: "marketeq:delete-alt-2",
      pencil: "marketeq:edit-alt-6",
      heart: "marketeq:favourite",
      home: "marketeq:home-alt-3",
      photo: "marketeq:gallery",
      logout: "marketeq:log-in",
      map: "marketeq:maps",
      "map-1": "marketeq:maps-location",
      "photo-1": "marketeq:mountain",
      search: "marketeq:search-alt-3",
    },
  },
}
