name: Deploy Playground
on:
  workflow_dispatch:
  push:
    branches: [main]
    # paths:
    # - "./.playground/**"
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Transfer backend files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./.playground"
          #target: ${{vars.SERVER_PATH}}
          target: "~/apps/ui/"
          strip_components: 2
  restart:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check package.json changes
        id: changed-packagejson
        uses: tj-actions/changed-files@v35
        with:
          files: package.json
      - name: Install + Restart pm2 process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            if ${{ steps.changed-packagejson.outputs.any_changed == 'true' }}; then
              npm install
            fi
              pm2 restart troll-ui
