name: Deploy Playground
on:
  workflow_dispatch:
  push:
    branches: [main]
    # paths:
    # - "./.playground/**"
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Transfer backend files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./.playground"
          #target: ${{vars.SERVER_PATH}}
          target: "~/apps/ui/"
          strip_components: 2
  build:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: SSH to install dependencies and build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/apps/ui
            echo "Installing dependencies..."
            npm install
            echo "Building Nuxt app..."
            npm run build
  restart:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Restart PM2 process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Restarting PM2 process..."
            pm2 restart troll-ui
